default:
    proso_models:
        mastery_threshold: 0.9
        predictive_model:
            class: proso.models.prediction.PriorCurrentPredictiveModel
        option_selector:
            class: proso.models.option_selection.ConfusingOptionSelection
            parameters:
              max_options: 3
              allow_zero_options_restriction: True
    proso_feedback:
        send_emails: false
        domain: localhost
        to:
            - root@localhost
    proso_common:
        logging:
            js_errors: true
    proso_tests:
        a:
            b:
                c: blah
        instantiate_ok:
            inner:
                class: proso_common.config_test.TestClass
                parameters:
                    dummy: ok
        instantiate_nok:
            class: proso_common.config_test.TestClass
    proso_common:
        logging:
            js_errors: true
    proso_flashcards:
        practice:
            common:
                set_length: 10
                fc_queue_size_max: 1
                fc_queue_size_min: 1
                save_answer_immediately: false
                cache_context: false
            intro:
                set_length: 5
                fc_queue_size_max: 5
                fc_queue_size_min: 3
                save_answer_immediately: true
                cache_context: true
